<?php // this is an autogenerated file - do not edit (created ___CREATED___) - to regenerate, use compileAutoload command in cli
defined('FRAMEWORK_DIR') or die('Invalid script access');

$autoload = array(
         ___CLASSLIST___
      );
