<?php // this is an autogenerated file - do not edit (created ___CREATED___) - to regenerate, use compileActionsMap command in cli
defined('FRAMEWORK_DIR') or die('Invalid script access');

$actionsMap = array(
         ___CLASSLIST___
      );
