<?php // this is an autogenerated file - do not edit (created ___CREATED___) - to regenerate, use compileConfig command in cli
defined('FRAMEWORK_DIR') or die('Invalid script access');

$config = array(
         ___CLASSLIST___
      );
