<?php
defined('FRAMEWORK_DIR') or die('Invalid script access');

$autoload = array(
    '\Framework\Core'       => FRAMEWORK_DIR.DS.'Core.php',
         'framework\\config' => FRAMEWORK_DIR.DS.'Config.php',
         'framework\\controllerexception' => FRAMEWORK_DIR.DS.'Controller.php',
         'framework\\controller' => FRAMEWORK_DIR.DS.'Controller.php',
         'framework\\coreexception' => FRAMEWORK_DIR.DS.'Core.php',
         'framework\\core' => FRAMEWORK_DIR.DS.'Core.php',
         'framework\\errorhandler' => FRAMEWORK_DIR.DS.'ErrorHandler.php',
         'framework\\loggerexception' => FRAMEWORK_DIR.DS.'Logger.php',
         'framework\\logger' => FRAMEWORK_DIR.DS.'Logger.php',
         'framework\\modelexception' => FRAMEWORK_DIR.DS.'Model.php',
         'framework\\model' => FRAMEWORK_DIR.DS.'Model.php',
         'application\\modules\\cli\\cliutils' => FRAMEWORK_DIR.DS.'modules'.DS.'cli'.DS.'CliUtils.php',
         'application\\modules\\cli\\controllers\\cliautoloadexception' => FRAMEWORK_DIR.DS.'modules'.DS.'cli'.DS.'controllers'.DS.'Autoload.php',
         'application\\modules\\cli\\controllers\\cliautoload' => FRAMEWORK_DIR.DS.'modules'.DS.'cli'.DS.'controllers'.DS.'Autoload.php',
         'application\\modules\\cli\\controllers\\cliexception' => FRAMEWORK_DIR.DS.'modules'.DS.'cli'.DS.'controllers'.DS.'Command.php',
         'application\\modules\\cli\\controllers\\clicommand' => FRAMEWORK_DIR.DS.'modules'.DS.'cli'.DS.'controllers'.DS.'Command.php',
         'application\\modules\\cli\\controllers\\cliconfigexception' => FRAMEWORK_DIR.DS.'modules'.DS.'cli'.DS.'controllers'.DS.'Config.php',
         'application\\modules\\cli\\controllers\\cliconfig' => FRAMEWORK_DIR.DS.'modules'.DS.'cli'.DS.'controllers'.DS.'Config.php',
         'application\\modules\\cli\\controllers\\cligenericexception' => FRAMEWORK_DIR.DS.'modules'.DS.'cli'.DS.'controllers'.DS.'Generic.php',
         'application\\modules\\cli\\controllers\\cligeneric' => FRAMEWORK_DIR.DS.'modules'.DS.'cli'.DS.'controllers'.DS.'Generic.php',
         'framework\\requestexception' => FRAMEWORK_DIR.DS.'Request.php',
         'framework\\request' => FRAMEWORK_DIR.DS.'Request.php',
         'framework\\responseexception' => FRAMEWORK_DIR.DS.'Response.php',
         'framework\\response' => FRAMEWORK_DIR.DS.'Response.php',
         'framework\\routeexception' => FRAMEWORK_DIR.DS.'Route.php',
         'framework\\route' => FRAMEWORK_DIR.DS.'Route.php',
         'framework\\utils\\classloaderexception' => FRAMEWORK_DIR.DS.'utils'.DS.'ClassLoader.php',
         'framework\\utils\\classloader' => FRAMEWORK_DIR.DS.'utils'.DS.'ClassLoader.php',
         'framework\\viewexception' => FRAMEWORK_DIR.DS.'View.php',
         'framework\\view' => FRAMEWORK_DIR.DS.'View.php'
    );