<?php
defined('FRAMEWORK_DIR') or die('Invalid script access');

$autoload = array(
         'theseer\\tools\\autoloadbuilder' => VENDORS_DIR.DS.'theseer'.DS.'autoload'.DS.'autoloadbuilder.php',
         'theseer\\tools\\autoloadbuilderexception' => VENDORS_DIR.DS.'theseer'.DS.'autoload'.DS.'autoloadbuilder.php',
         'theseer\\tools\\autoloadbuildercli' => VENDORS_DIR.DS.'theseer'.DS.'autoload'.DS.'autoloadbuildercli.php',
         'theseer\\tools\\classfinder' => VENDORS_DIR.DS.'theseer'.DS.'autoload'.DS.'classfinder.php',
         'theseer\\tools\\phpfilteriterator' => VENDORS_DIR.DS.'theseer'.DS.'autoload'.DS.'phpfilter.php',
         'theseer\\tools\\directoryscanner' => VENDORS_DIR.DS.'theseer'.DS.'scanner'.DS.'directoryscanner.php',
         'theseer\\tools\\directoryscannerexception' => VENDORS_DIR.DS.'theseer'.DS.'scanner'.DS.'directoryscanner.php',
         'theseer\\tools\\filesonlyfilteriterator' => VENDORS_DIR.DS.'theseer'.DS.'scanner'.DS.'filesonlyfilter.php',
         'theseer\\tools\\includeexcludefilteriterator' => VENDORS_DIR.DS.'theseer'.DS.'scanner'.DS.'includeexcludefilter.php',
         'framework\\config' => FRAMEWORK_DIR.DS.'Config.php',
         'framework\\controllerexception' => FRAMEWORK_DIR.DS.'Controller.php',
         'framework\\controller' => FRAMEWORK_DIR.DS.'Controller.php',
         'framework\\coreexception' => FRAMEWORK_DIR.DS.'Core.php',
         'framework\\core' => FRAMEWORK_DIR.DS.'Core.php',
         'framework\\errorhandler' => FRAMEWORK_DIR.DS.'ErrorHandler.php',
         'framework\\loggerexception' => FRAMEWORK_DIR.DS.'Logger.php',
         'framework\\logger' => FRAMEWORK_DIR.DS.'Logger.php',
         'framework\\modelexception' => FRAMEWORK_DIR.DS.'Model.php',
         'framework\\model' => FRAMEWORK_DIR.DS.'Model.php',
         'application\\modules\\cli\\cliutils' => FRAMEWORK_DIR.DS.'modules'.DS.'cli'.DS.'CliUtils.php',
         'application\\modules\\cli\\controllers\\cliautoloadexception' => FRAMEWORK_DIR.DS.'modules'.DS.'cli'.DS.'controllers'.DS.'Autoload.php',
         'application\\modules\\cli\\controllers\\cliautoload' => FRAMEWORK_DIR.DS.'modules'.DS.'cli'.DS.'controllers'.DS.'Autoload.php',
         'application\\modules\\cli\\controllers\\cliexception' => FRAMEWORK_DIR.DS.'modules'.DS.'cli'.DS.'controllers'.DS.'Command.php',
         'application\\modules\\cli\\controllers\\clicommand' => FRAMEWORK_DIR.DS.'modules'.DS.'cli'.DS.'controllers'.DS.'Command.php',
         'application\\modules\\cli\\controllers\\cliconfigexception' => FRAMEWORK_DIR.DS.'modules'.DS.'cli'.DS.'controllers'.DS.'Config.php',
         'application\\modules\\cli\\controllers\\cliconfig' => FRAMEWORK_DIR.DS.'modules'.DS.'cli'.DS.'controllers'.DS.'Config.php',
         'application\\modules\\cli\\controllers\\cligenericexception' => FRAMEWORK_DIR.DS.'modules'.DS.'cli'.DS.'controllers'.DS.'Generic.php',
         'application\\modules\\cli\\controllers\\cligeneric' => FRAMEWORK_DIR.DS.'modules'.DS.'cli'.DS.'controllers'.DS.'Generic.php',
         'framework\\requestexception' => FRAMEWORK_DIR.DS.'Request.php',
         'framework\\request' => FRAMEWORK_DIR.DS.'Request.php',
         'framework\\responseexception' => FRAMEWORK_DIR.DS.'Response.php',
         'framework\\response' => FRAMEWORK_DIR.DS.'Response.php',
         'framework\\utils\\routeexception' => FRAMEWORK_DIR.DS.'utils'.DS.'Route.php',
         'framework\\utils\\route' => FRAMEWORK_DIR.DS.'utils'.DS.'Route.php',
         'framework\\utils\\classloaderexception' => FRAMEWORK_DIR.DS.'utils'.DS.'ClassLoader.php',
         'framework\\utils\\classloader' => FRAMEWORK_DIR.DS.'utils'.DS.'ClassLoader.php',
         'framework\\viewexception' => FRAMEWORK_DIR.DS.'View.php',
         'framework\\view' => FRAMEWORK_DIR.DS.'View.php'
    );